version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      # Check for updates once a week
      interval: 'weekly'
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      docker:
        patterns:
          - "*"
